<?php

namespace ApuestasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JugadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JugadorRepository extends EntityRepository
{
}
